### ISSUE TITLE
Example logs error, but doesn't do anything with it.

### ISSUE THREAD

**Issue by TheCyberRonin** [ytb2mp3/youtube-mp3-downloader#14]
I'm pretty much using your example, and it works wonderfully. With the exception that it doesn't actually do anything with an error besides log it to console and then go on and crash because it continues even though there is an error.
From what I understand, if there is an error there should be a callback returning the error. How could I get the callback and return an error when it occurs when I don't have access to the data to retrieve the callback?
Any help would be appreciated 😄

**Comment by tobilg** [comment]
Thanks for reporting. Can you please show the code you're using?

**Comment by TheCyberRonin** [comment]
``` js
const ytdl = require('youtube-mp3-downloader');

const Downloader = function(loc) {
    var self = this;

    self.YD = new ytdl({
        "ffmpegPath": loc,        // Where is the FFmpeg binary located?
        "outputPath": "mp3",                 // Where should the downloaded and encoded files be stored? 
        "youtubeVideoQuality": "highest",       // What video quality should be used? 
        "queueParallelism": 2,                  // How many parallel downloads/encodes should be started? 
        "progressTimeout": 2000                 // How long should be the interval of the progress reports 
    });

    self.callbacks = {};

    self.YD.on("finished", function(data) {

        if (self.callbacks[data.videoId]) {
            self.callbacks[data.videoId](null,"update");
        } else {
            console.log("Error: No callback for videoId!");
        }

    });

    self.YD.on("error", function(error) {
        console.log(error);

    });

}

Downloader.prototype.getMP3 = function(id, title, callback){
    var self = this;

    // Register callback
    self.callbacks[id] = callback;
    // Trigger download
    self.YD.download(id, title);

}

module.exports = Downloader;
```

It seems that on error it properly shows the error in console, but is there a way to call the error in the callback?

**Comment by TheCyberRonin** [comment]
I'm pretty much just using a slightly modified version of your example usage.

**Comment by tobilg** [comment]
Well, but which circumstances trigger the behavior? I.e. how do you use this code? When exactly does the error occur?

**Comment by TheCyberRonin** [comment]
On any error it just outputs to console. There is no callback for the error. For instance, this way bombs out if I can't download it because it's region restricted. 

```
Code 150: This video contains content from SME, who has blocked it in your country on copyright grounds.                                                                                                    
C:\Users\rswyers\Documents\HawkBot\node_modules\youtube-mp3-downloader\lib\YoutubeMp3Downloader.js:80                                                                                                       
        var videoTitle = self.cleanFileName(info.title);                                                                                                                                                    
                                                ^                                                                                                                                                           

TypeError: Cannot read property 'title' of undefined                                                                                                                                                        
    at C:\Users\rswyers\Documents\HawkBot\node_modules\youtube-mp3-downloader\lib\YoutubeMp3Downloader.js:80:49                                                                                             
    at gotConfig (C:\Users\rswyers\Documents\HawkBot\node_modules\ytdl-core\lib\info.js:128:5)                                                                                                              
    at C:\Users\rswyers\Documents\HawkBot\node_modules\ytdl-core\lib\info.js:111:5                                                                                                                          
    at checkDone (C:\Users\rswyers\Documents\HawkBot\node_modules\ytdl-core\lib\util.js:306:7)                                                                                                              
    at C:\Users\rswyers\Documents\HawkBot\node_modules\ytdl-core\lib\info.js:77:13                                                                                                                          
    at IncomingMessage.<anonymous> (C:\Users\rswyers\Documents\HawkBot\node_modules\ytdl-core\lib\request.js:42:9)                                                                                          
    at emitNone (events.js:91:20)                                                                                                                                                                           
    at IncomingMessage.emit (events.js:185:7)                                                                                                                                                               
    at endReadableNT (_stream_readable.js:975:12)                                                                                                                                                           
    at _combinedTickCallback (internal/process/next_tick.js:74:11)                            
```

So my particular use case I actually fork a process that is sent data whenever I request something from YouTube to be downloaded, the fork handles it by calling getmp3, if it errors out it should send a message back to the parent with a code of 1. If it goes through properly it'll send a code 0 and some data back. It never gets to the point because there is no callback for the error, I'm unsure how to match the error with the callback[id] that is created.  
Code for reference.

``` js
"use strict";

const Downloader = require("./lib/Downloader.js");
const dl = new Downloader();
const yID = process.argv[2];
const title = process.argv[3];

process.on('message', function(m)
{
  dl.getMP3(m.id, m.file, function(err, result)
  {
    if(err)
    {
      process.send({status: 1});
    }
    else
    {
      process.send({status: 0, title: m.title, file: m.file});
    }
  });
});
```

**Comment by TheCyberRonin** [comment]
``` js
    self.YD.on("error", function(error) {
        console.log(error);
    });
```

This is the portion that I'm mainly referring to. I think there should be a way to return the callback(error), but I can't really think of a way to find the particular callback to return the error to. That's really the only way that any error will be returned in the getmp3 callback, correct?

**Comment by tobilg** [comment]
Fixed in version `0.4.4`

**Comment by TheCyberRonin** [comment]
Will you by any chance be uploading that to npm? I appreciate your help, by the way! 😄

**Comment by tobilg** [comment]
I did so already.
