### ISSUE TITLE
did you see this problem ?

### ISSUE THREAD

**Issue by wahengchang** [ytb2mp3/youtube-mp3-downloader#16]
C02T30AMG8WL-lm:ex1 peterchang$ node youtube-mp3-download.js 
internal/child_process.js:313
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:1023:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:387:9)
    at /Users/peterchang/Desktop/node/soundcloud/ex1/node_modules/fluent-ffmpeg/lib/processor.js:135:24
    at FfmpegCommand.proto._getFfmpegPath (/Users/peterchang/Desktop/node/soundcloud/ex1/node_modules/fluent-ffmpeg/lib/capabilities.js:90:14)
    at FfmpegCommand.proto._spawnFfmpeg (/Users/peterchang/Desktop/node/soundcloud/ex1/node_modules/fluent-ffmpeg/lib/processor.js:115:10)
    at FfmpegCommand.proto.availableFormats.proto.getAvailableFormats (/Users/peterchang/Desktop/node/soundcloud/ex1/node_modules/fluent-ffmpeg/lib/capabilities.js:514:10)
    at /Users/peterchang/Desktop/node/soundcloud/ex1/node_modules/fluent-ffmpeg/lib/capabilities.js:564:14
    at fn (/Users/peterchang/Desktop/node/soundcloud/ex1/node_modules/async/lib/async.js:582:34)
    at Immediate.<anonymous> (/Users/peterchang/Desktop/node/soundcloud/ex1/node_modules/async/lib/async.js:498:34)

**Comment by tobilg** [comment]
No, and you don't show example code. How should I know what you were doing?

**Comment by tobilg** [comment]
Also, see https://github.com/tobilg/youtube-mp3-downloader/issues/6
