### ISSUE TITLE
Uncaught errors

### ISSUE THREAD

**Issue by SirDeadlystrike** [ytb2mp3/youtube-mp3-downloader#19]
YD.on("error", function(error) {
    console.log(error);
});

This method of catching a error with a download is not catching errors with YTDL such as 

(Mini-Get is the http GET client used by ytdl-core)
`2017-07-12 07:52 -05:00: Error: Status code: 500
    at ClientRequest.<anonymous> (sanatized-path\node_modules\miniget\lib\index.js:65:17)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:564:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at TLSSocket.socketOnData (_http_client.js:453:20)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at TLSSocket.Readable.push (_stream_readable.js:197:10)
    at TLSWrap.onread (net.js:588:20)`

**Comment by tobilg** [comment]
`ytdl-core` is not emitting error events, and the error above is from a submodule. Not sure what your expectations are to be honest....

**Comment by SirDeadlystrike** [comment]
Hmm, ok i guess i misunderstood. At the moment i only interface with ytdl-core through this package. I thought that maybe the downloader would throw an error ... nvm your 100% right ytdl-core is not even throwing the error, idk why i even through this would catch it, im sleep deprived - forget i was here
