### ISSUE TITLE
Err: Too many reconnects

### ISSUE THREAD

**Issue by limsammy** [ytb2mp3/youtube-mp3-downloader#26]
I get the following error when downloading certain youtube videos. It seems to get a certain percentage of the video and then it fails, on this playlist usually around 100-200 songs in, never the same song. Is there a way to skip the break out of the download function if the percentage gets stuck? https://www.youtube.com/playlist?list=PLJKDxKDJBeYnen4wYXDY8jhlcZsDAsaT6

```
events.js:136
      throw er; // Unhandled 'error' event
      ^

Error: Too many reconnects
    at doDownload (/Users/sam/personal/youtubejoel/node_modules/ytdl-core/lib/index.js:110:26)
    at PassThrough.onend (/Users/sam/personal/youtubejoel/node_modules/ytdl-core/lib/index.js:152:7)
    at PassThrough.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1054:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by ytb2mp3** [comment]
Can you please elaborate how you use the package in your code? Thanks
