### ISSUE TITLE
Error: spawn EACCES

### ISSUE THREAD

**Issue by anhtrung0000** [ytb2mp3/youtube-mp3-downloader#28]
hi. hope u have mme at this error.
when i use "node index.js" to run that script . this error show:
$ node index.js
internal/child_process.js:330
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at ChildProcess.spawn (internal/child_process.js:330:11)
    at exports.spawn (child_process.js:500:9)
    at /Users/trungnq/Projects/myplan/ytdownloader/node_modules/fluent-ffmpeg/lib/processor.js:152:24
    at FfmpegCommand.proto._getFfmpegPath (/Users/trungnq/Projects/myplan/ytdownloader/node_modules/fluent-ffmpeg/lib/capabilities.js:90:14)
    at FfmpegCommand.proto._spawnFfmpeg (/Users/trungnq/Projects/myplan/ytdownloader/node_modules/fluent-ffmpeg/lib/processor.js:132:10)
    at FfmpegCommand.proto.availableFormats.proto.getAvailableFormats (/Users/trungnq/Projects/myplan/ytdownloader/node_modules/fluent-ffmpeg/lib/capabilities.js:517:10)
    at /Users/trungnq/Projects/myplan/ytdownloader/node_modules/fluent-ffmpeg/lib/capabilities.js:568:14
    at nextTask (/Users/trungnq/Projects/myplan/ytdownloader/node_modules/async/dist/async.js:5310:14)
    at Object.waterfall (/Users/trungnq/Projects/myplan/ytdownloader/node_modules/async/dist/async.js:5320:5)
    at FfmpegCommand.proto._checkCapabilities (/Users/trungnq/Projects/myplan/ytdownloader/node_modules/fluent-ffmpeg/lib/capabilities.js:565:11)
How to fix that? thank u!

**Comment by nulldreams** [comment]
Hey, @ anhtrung0000!
I have the same problem in Heroku, I think this error occurs because the machine does not have **ffmpeg**.
On my computer (windows), I have **ffmpeg.exe** and it works.

**Comment by ytb2mp3** [comment]
@anhtrung0000 You need to have ffmpeg installed, as outlined at https://github.com/ytb2mp3/youtube-mp3-downloader#prerequisites Please verify and close if that was the problem. Thanks!
