### ISSUE TITLE
Error spawn ENOENT

### ISSUE THREAD

**Issue by Spodera** [ytb2mp3/youtube-mp3-downloader#59]
Every time I try to download, I receive this specific error : 

````
Error: spawn D:/User/Documents/Programming/project/src/downloads/youtube-mp3/ffmpeg ENOENT
        at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
        at onErrorNT (internal/child_process.js:468:16)
        at processTicksAndRejections (internal/process/task_queues.js:80:21) {
      errno: -4058,
      code: 'ENOENT',
      syscall: 'spawn D:/User/Documents/Programming/project/src/downloads/youtube-mp3/ffmpeg',
      path: 'D:/User/Documents/Programming/project/src/downloads/youtube-mp3/ffmpeg',
      spawnargs: [ '-formats' ]
    }
````
This folder existed yet, how can i fix this error ?

**Comment by fdciabdul** [comment]
are you have ffmpeg installed on your system and was setting the ffmpeg environtment variable ?

**Comment by Spodera** [comment]
Yes, I added the ffmpeg/bin path to the ``System Variables`` > ``Path``  section (on windows)

**Comment by Nevah5** [comment]
Would like to have more information to the fix @Spodera
