### ISSUE TITLE
TypeError: Cannot read property 'videoDetails' of undefined | MinigetError: Status code: 429

### ISSUE THREAD

**Issue by vikram-sapate** [ytb2mp3/youtube-mp3-downloader#78]
```
0|app    | TypeError: Cannot read property 'videoDetails' of undefined
0|app    |     at YoutubeMp3Downloader.performDownload (/home/ubuntu/server/node_modules/youtube-mp3-downloader/lib/YoutubeMp3Downloader.js:86:50)
0|app    |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
0|app    | GrAchTdepsU
0|app    | MinigetError: Status code: 429
0|app    |     at ClientRequest.<anonymous> (/home/ubuntu/server/node_modules/miniget/dist/index.js:190:31)
0|app    |     at Object.onceWrapper (events.js:422:26)
0|app    |     at ClientRequest.emit (events.js:315:20)
0|app    |     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
0|app    |     at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
0|app    |     at TLSSocket.socketOnData (_http_client.js:469:22)
0|app    |     at TLSSocket.emit (events.js:315:20)
0|app    |     at addChunk (_stream_readable.js:295:12)
0|app    |     at readableAddChunk (_stream_readable.js:271:9)
0|app    |     at TLSSocket.Readable.push (_stream_readable.js:212:10)
0|app    |     at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23) {
0|app    |   statusCode: 429
0|app    | }

```

**Comment by vikram-sapate** [comment]
Solved. No issue with youtube-mp3-downloader, ytdl-core or minigent npm.
YouTube blocks you if you send too many requests. Just change public IP.
