### ISSUE TITLE
ERROR YTMP3 MinigetError: Status code: 403

### ISSUE THREAD

**Issue by vinioliv** [ytb2mp3/youtube-mp3-downloader#99]
at ClientRequest.<anonymous> (D:\Projetos\MusicApp\MusicApp\backend\node_modules\miniget\src\index.ts:257:19)
    at Object.onceWrapper (events.js:482:26)
    at ClientRequest.emit (events.js:375:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at HTTPParser.execute (<anonymous>)
    at TLSSocket.socketOnData (_http_client.js:515:22)
    at TLSSocket.emit (events.js:375:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
[ERROR] 01:42:44 Error: Status code: 403

**Comment by tobilg** [comment]
Can't reproduce
